species: mus_musculus
tiger:
  model_path: models/tiger_model
  calibration_params: models/calibration.pkl
  scoring_params: models/scoring.pkl
  batch_size: 128
  guide_length: 23
  context_5p: 3
  context_3p: 0
offtarget:
  reference_transcriptome: reference/sample_reference.fa
  max_mismatches: 3
  binary_path: bin/offtarget_search
  chunk_size: 500
filtering:
  top_n_guides: 3
  min_guide_score: 0.4
  mm1_threshold: 5
  mm2_threshold: 5
  adaptive_mm0: false
  mm0_tolerance: 999
output:
  validate_mm0_locations: false
slurm:
  account: sanjana
  partition: cpu
  time: 00:05:00
  mem: 4G
  cpus_per_task: 1
ensembl:
  rest_url: https://rest.ensembl.org
  prefer_canonical: true
  prefer_appris_principal: true
  rate_limit_delay: 0.5
compute:
  threads: 1
  memory_gb: 4
  use_gpu: false
top_n_guides: 10
output_dir: output_smoke
threads: 1
