name: Package Tests

on:
  push:
    paths:
      - 'tiger_guides_pkg/**'
      - '.github/workflows/package-tests.yml'
      - 'scripts/**'
      - 'src/**'
  pull_request:
    paths:
      - 'tiger_guides_pkg/**'
      - '.github/workflows/package-tests.yml'
      - 'scripts/**'
      - 'src/**'

jobs:
  tests:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Install package (editable) with dev extras
        working-directory: tiger_guides_pkg
        run: |
          pip install --upgrade pip
          pip install -e .[dev]

      - name: Build off-target binary (for tests requiring it)
        working-directory: tiger_guides_pkg/c/offtarget
        run: make

      - name: Run unit tests
        working-directory: tiger_guides_pkg
        run: pytest tests/unit -q

      - name: Run integration tests (no network)
        working-directory: tiger_guides_pkg
        env:
          PYTHONPATH: ${{ github.workspace }}/tiger_guides_pkg/src
          PATH: ${{ github.workspace }}/tiger_guides_pkg/c/offtarget:${PATH}
        run: pytest tests/integration -m "not network" -q

      - name: Upload pytest results (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-logs-${{ matrix.python-version }}
          path: tiger_guides_pkg/.pytest_cache
          if-no-files-found: ignore
